# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elephant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Haplotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.TextField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('locationType', models.TextField()),
                ('matchNotes', models.TextField()),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='haplotype',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Publications'),
        ),
        migrations.AddField(
            model_name='elephant',
            name='haplotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Haplotype'),
        ),
        migrations.AddField(
            model_name='elephant',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Location'),
        ),
    ]
