# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_auto_20170129_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='elephants',
            name='genebankAccession',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
