# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_elephants_genebankaccession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haplotypes',
            name='author',
        ),
        migrations.AddField(
            model_name='elephants',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Publications'),
        ),
        migrations.AlterField(
            model_name='elephants',
            name='haplotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Sequences'),
        ),
        migrations.DeleteModel(
            name='Haplotypes',
        ),
    ]
