# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_auto_20170212_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='accuracy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
