# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_locations_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='paperurl',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
