# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0008_publications_paperurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='elephants',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='elephants',
            name='lastChanged',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='lastChanged',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='lastChanged',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequences',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sequences',
            name='lastChanged',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
