# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0009_auto_20171001_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='sequences',
            name='enabled',
        ),
        migrations.AddField(
            model_name='locations',
            name='oldPk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='oldPk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sequences',
            name='oldPk',
            field=models.IntegerField(null=True),
        ),
    ]
