# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0010_auto_20171013_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elephants',
            name='enabled',
        ),
        migrations.AddField(
            model_name='elephants',
            name='oldPk',
            field=models.IntegerField(null=True),
        ),
    ]
