# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0011_auto_20171013_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elephants',
            name='lastChanged',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='lastChanged',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publications',
            name='lastChanged',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='lastChanged',
            field=models.DateTimeField(),
        ),
    ]
