# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0012_auto_20171013_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elephants',
            name='lastChanged',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='lastChanged',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='lastChanged',
        ),
        migrations.RemoveField(
            model_name='sequences',
            name='lastChanged',
        ),
        migrations.AddField(
            model_name='elephants',
            name='datetimeModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 19, 12, 19, 505897)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='datetimeModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 19, 12, 21, 484980)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='datetimeModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 19, 12, 23, 967931)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequences',
            name='datetimeModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 19, 12, 27, 153692)),
            preserve_default=False,
        ),
    ]
