# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0013_auto_20171013_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='elephants',
            name='lastEditNotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='elephants',
            name='lastEditedBy',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='lastEditNotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='lastEditedBy',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='lastEditNotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='lastEditedBy',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sequences',
            name='lastEditNotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sequences',
            name='lastEditedBy',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
