# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0015_auto_20171215_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='LHPIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genBankAccess', models.CharField(max_length=30)),
                ('datetimeModified', models.DateTimeField()),
                ('lastEditedBy', models.CharField(max_length=30, null=True)),
                ('lastEditNotes', models.TextField(null=True)),
                ('LHP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.LocHapPub')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.Publications')),
            ],
        ),
    ]
