# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0016_lhpindividual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lhpindividual',
            old_name='genBankAccess',
            new_name='genBankAccession',
        ),
    ]
