# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0017_auto_20171215_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lhpindividual',
            name='author',
        ),
        migrations.AddField(
            model_name='lhpindividual',
            name='numElephants',
            field=models.IntegerField(null=True),
        ),
    ]
