# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0018_auto_20171215_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lochappub',
            name='genebankAccession',
        ),
    ]
