# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-09 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0019_remove_lochappub_genebankaccession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lhpindividual',
            name='genBankAccession',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
